name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Setup
        run: make setup

      - name: Clean
        run: make clean

      - name: Build
        run: make build ENVIRONMENT=production
        env:
          API_HOST: ${{ secrets.API_HOST }}

      - name: Deploy
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
