name: test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "src/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Install dependencies
        run: make install

      - name: Lint
        run: make lint

      - name: Type check
        run: make typecheck

      - name: Format, not write
        run: make fmt
